config/routes.rb
Rails.application.routes.draw do
  # ELBヘルスチェック用エンドポイント（認証不要）
  get "health" => "rails/health#show", as: :rails_health_check

  root to: 'reports#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/sign_out', to: 'users/sessions#destroy'
    resources :users do
      member do
        patch 'revive'
      end
    end
  end

  resources :reports do
    collection do
      resource :summary, only: %i(show), module: :reports
      resource :unsubmitted, only: %i(show), module: :reports
    end
  end
  resources :projects do
    resources :members, only: %i(index update destroy), module: :projects
  end
  resources :estimates, only: %i(index create) do
    collection do
      post :confirm
    end
  end
  resources :bills, only: %i(index create) do
    collection do
      post :confirm
    end
  end

  namespace :settings do
    resources :projects, only: %i(index update destroy)
    resource :password, only: %i(show update)
    resources :api_tokens, only: %i(index create destroy)
  end

  scope :admin do
    root to: 'admin#index', as: :admin_root
  end

  namespace :admin do
    resources :csvs, only: %i(index)
  end

  namespace :projects do
    get 'members/edit'
  end

  # システム管理画面
  namespace :system_admin do
    root to: 'dashboard#index'
    resources :users do
      member do
        patch :revive
        patch :toggle_role
      end
    end
    resources :projects do
      resources :members, only: %i(index create destroy), module: :projects
    end
    resources :reports, only: %i(index show edit update destroy) do
      collection do
        get :summary
        get :unsubmitted
      end
    end
    resources :estimates do
      collection do
        post :confirm
      end
    end
    resources :bills do
      collection do
        post :confirm
      end
    end
    resources :user_roles, only: %i(index show)
    resources :csvs, only: %i(index)
    resources :retirement_processings, only: %i(index create show) do
      member do
        post :cancel
      end
    end
  end
end

app/views/admin/index.html.slim
h1 管理画面

dl.dl-horizontal
  dt
    = link_to 'プロジェクト管理', projects_path(active: true, order: 'code_desc')
  dd 日報に登録するプロジェクトを管理します。
  /
    dt
      = link_to '見積書アップロード', estimates_path
    dd 見積書ファイルをアップロードします。
    dt
      = link_to '請求書アップロード', bills_path
    dd 請求書ファイルをアップロードします。
  dt
    = link_to_if policy(current_user).index?, 'ユーザー管理', users_path
  dd ユーザーの一覧を表示し、登録や編集を行います。
  dt
    = link_to_if policy(current_user).csv?, 'CSV出力', admin_csvs_path
  dd 各種データをCSV形式でダウンロードします。
  dt
    = link_to_if policy(Report.new).summary?, '稼働集計', summary_path
  dd 全員の稼働を集計して表示します。
  dt
    = link_to_if policy(Report.new).unsubmitted?, '日報未提出一覧', unsubmitted_path
  dd 日報が未提出である日付をユーザーごとに一覧表示します。